services:
  - type: web
    name: matrimony-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node dist/main.js
    envVars:
      - key: DATABASE_URL
        sync: false